Issue 90: Fix for self-referential nested fields
plangrid/flask-rebar pull request #226
Opened 2021-01-21 01:39 UTC by PratikPramanik

2021-05-20 05:54 UTC, mrbaguvix approved these changes

2021-06-30 00:03 UTC, dblackdblack requested changes
Please add 50% more awesome

2021-06-30 00:04 UTC, RookieRick commented
> Please add 50% more awesome

We're cranking the `awesome` knob to 11 for this release! 😂

2021-06-30 00:07 UTC, RookieRick approved these changes
Since I hijacked Pratik's PR, I'm reviewing my changes on his behalf and he said 👍 so off we go! 😂

2021-06-30 00:09 UTC, merged